CREATE TABLE  `logentries` (
 `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 `created` DATETIME NOT NULL ,
 `event` VARCHAR( 12 ) NOT NULL ,
 `value` VARCHAR( 250 ) NOT NULL ,
 `data` TEXT NULL
) ENGINE = MYISAM ;